config/routes.rb
Rails.application.routes.draw do

  
  get "log_out" => "logins#destroy", :as => "log_out"
  
  get "my_account" => "users#my_account"
    
  get "chnage_password" => "users#change_password"
  
  resources :users do
     get "delete"
     get "search_user_list"
     get "edit_department"
     post "update_department"
    collection { get :new_export }
   end
   
  resources :logins do
    
       
  end
 
  resources :sessions do
          get '/login' => 'sessions#new'
          post '/login' => 'sessions#create'
          get "index"
         
          post "new"
         
    end
     
  
   
  resources :users do
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end
     
  resources :employees do
    get "import_index"
      collection { post :import }
     end
   
   resources :time_sheets do
    
       collection { post :import }
   end  
      
     
     get "time_home" => 'time_reports#time_home'
  
  resources :departments_users do
      
     
     collection { get :edit }
    end  
     
 root :to => "sessions#new"
      
      
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def login
     render :action => new,:layout=>false
  end
  
  def new
    render :layout=> false
  end
 
 def create
 
   user = User.authenticate(params[:User][:user_name], params[:User][:password])
   if user
     session[:user_id] = user.id
     logged_in_user = User.find_by_id(user.id)
     
     new_login_details = LoginDetail.new(:user_id => logged_in_user.id  , :login_time => Time.now , :remarks => "Active")
   
     new_login_details.save!
     session[:login] = new_login_details.id
      
    
     redirect_to :action => 'index', :controller=>"users",:notice => "Logged in!"
 
       
   else
    
     flash[:notice] = "Invalid User/Password Combination."
     redirect_to root_url
 
   end
 end
 
 def destroy
  
   session[:user_id] = nil
     
   redirect_to root_url  #, :notice => "Logged out!"
 end
 
 
 def show
  render :action => 'new',:layout=> false
 end
  
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/views/logins/login.html.erb
<%= stylesheet_link_tag "style" %>

<%= javascript_include_tag "application" %>

app/views/logins/new.html.erb
<%= stylesheet_link_tag "style" %>

<%= javascript_include_tag "application" %>


<body class="clor">
<%= form_tag logins_path do %>

    <table width="510" border="0" align="center" cellpadding="0" cellspacing="0">
     
        <tr>
               <td height="77" align="center">&nbsp;</td>
        </tr>
        <tr>
               <td align="center"><img src="../images/Attendance Reporting System.png" width="353" height="37" /></td>
        </tr>
        <tr>
                <td height="10" align="center"></td>
        </tr>
        <tr>
                <td align="center" valign="top"><table width="500" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr>
           <td height="227" valign="top" background="../images/loginbg.jpg">
           
           <table width="92%" border="0" align="center" cellpadding="0" cellspacing="0">
           
            <tr>
                 <td height="46"><img src="../images/loginname.jpg" width="73" height="30" /></td>
            </tr>
            
            <tr>
                 <td>&nbsp;</td>
            </tr>
            <tr>
                   <td align="center" valign="middle">
               
             <table width="380" border="0" cellspacing="0" cellpadding="0">
               
             <tr>
				    <td colspan="2"><p id="flash_colour"><%= flash[:notice] %></p></td>
			 </tr>
             <tr>
    
                    <td><%=text_field 'User','user_name',:class=>"logintext",:value=>"User name" ,:onFocus=>"if(this.value == 'User name') {this.value = '';}", :onBlur=>"if (this.value == '') {this.value = 'User name';}" %></td>
             </tr>
             <tr>
                    <td>&nbsp;</td>
             </tr>
             <tr>
    
                    <td><%= password_field 'User','password',:class=>"logintext",:value=>"Password" ,:onFocus=>"if(this.value == 'Password') {this.value = '';}", :onBlur=>"if (this.value == '') {this.value = 'Password';}"%></td>
             </tr>
             <tr>
                   <td height="30">&nbsp;</td>
             </tr>
             <tr>
                   <td><table width="388" border="0" cellspacing="0" cellpadding="0">
             <tr>
        
                    <td width="87" , align="right"><%= image_submit_tag ("login.jpg"),:id=>"submit",:onclick=>"check_empty()"  %></td>
        
             </tr>
     
             </table>
    
          </td>
        </tr>
    
            </table>
             </td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
 
  <% end %>
</table>

</body>

<script>

   function check_empty() {
    //alert('hi');
        if (document.getElementById('User_user_name').value == ""  {
                alert("Fill All Fields !");
         } else {
                 document.getElementById('form').submit();
              alert("Form Submitted Successfully...");
         }
     }
     
  


</script>

app/views/logins/show.html.erb
<%= stylesheet_link_tag "style" %>




<body class="clor">


</body>