config/routes.rb
Rails.application.routes.draw do

  
  get "log_out" => "logins#destroy", :as => "log_out"
  
  get "my_account" => "users#my_account"
    
  get "chnage_password" => "users#change_password"
  
  resources :users do
     get "delete"
     get "search_user_list"
     get "edit_department"
     post "update_department"
    collection { get :new_export }
   end
   
  resources :logins do
    
       
  end
 
  resources :sessions do
          get '/login' => 'sessions#new'
          post '/login' => 'sessions#create'
          get "index"
         
          post "new"
         
    end
     
  
   
  resources :users do
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end
     
  resources :employees do
    get "import_index"
      collection { post :import }
     end
   
   resources :time_sheets do
    
       collection { post :import }
   end  
      
     
     get "time_home" => 'time_reports#time_home'
  
  resources :departments_users do
      
     
     collection { get :edit }
    end  
     
 root :to => "sessions#new"
      
      
end

app/models/departments_user.rb
class DepartmentsUser < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_and_belongs_to_many :departments
  
  has_many :login_details
  has_many :user_departments
   
   attr_accessor :password
   before_save :encrypt_password
  
    validates_presence_of :first_name 
    validates_presence_of :last_name
    validates_presence_of :email
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
    validates_uniqueness_of :email
    #validates_presence_of :domain_name
    validates_uniqueness_of :domain_name
    
 # validates_uniqueness_of :user_name
    
   # validates_presence_of :is_admin, :message => "/User Type? should be selected"
  require 'rubygems'
  
  require 'net/ldap' # gem install ruby-net-ldap
  require 'csv'
  
  SERVER = '172.28.48.51'
  PORT = 389
  BASE = 'tandon.local'
  DOMAIN = 'tandon.local'
  credentials = {
    :method => :simple,
    :username =>'suhas.dabhade@tandon.local',
    :password => 'Infinx@10'
  }
  
  
  def self.domain_authenticates(username,password)
    
      ldap = Net::LDAP.new :host => SERVER,:port => PORT, :base => BASE, :domain => DOMAIN,:auth => {
                                                                                           :method => :simple,
                                                                                           :username => username,
                                                                                           :password => password
                                                                                           }
          
                            
      if ldap.bind 
        
       # and user = ldap.search(:filter => "sAMAccountName=#{username}")
       
              # Redundant? Sure - the code will be 0 and the message will be "Success".
        puts "Connection successful!  Code:  #{ldap.get_operation_result.code}, message: #{ldap.get_operation_result.message}"
       
        # GET THE DISPLAY NAME AND E-MAIL ADDRESS FOR A SINGLE USER
       # search_param = username
       # result_attrs = ["displayName"]
        
        # Build filter
       # search_filter = Net::LDAP::Filter.eq("sAMAccountName", search_param)
        
        # Execute search
       # if ldap.search(:filter => search_filter, :attributes => result_attrs, :return_result => false)
        #  puts "SUHAS DABHADE"
          return true
      #  else
       #   puts "DABHADE SUHAS"
       #   return false
      #  end
      #  puts 'i am outside'
        
      else
        
        puts "Connection failed!  Code:  #{ldap.get_operation_result.code}, message: #{ldap.get_operation_result.message}"
        return false
      end
      
     
      
    end
    
    def self.domain_search(user1)
     
      ldap = Net::LDAP.new :host => SERVER,
           :port => 389,
           :auth => {
                       :method => :simple,
                       :username => 'suhas.dabhade@tandon.local',
                       :password => 'Infinx@10'
                    }
                    
      filter = Net::LDAP::Filter.eq( "sAMAccountName", user1 )
    # raise filter.inspect
      treebase = "tandon.local"
      
      ldap.search( :base => treebase, :filter => filter ) do |entry|
      raise entry.inspect
        puts "DN: #{entry.dn}"
        entry.each do |attribute, values|
          puts "   #{attribute}:"
          values.each do |value|
            puts "      --->#{value}"
          end
        end
      end
                   
                    
    end
     
     
  def self.db_authenticates(user)
    # raise user.inspect
       user = find_by_domain_name_and_status(user,'Active')
      # raise user.inspect
       if user
         user
       else
         nil
       end
     end
  
  
  def self.authenticate(username, password)
    
     user = find_by_user_name(username)
     if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
       user
     else
       nil
     end
   end
   
   def encrypt_password
     if password.present?
       self.password_salt = BCrypt::Engine.generate_salt
       self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
     end
   end

  
  
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        
        csv << user.attributes.values
      end
    end
  end
 
    
  def self.search(search)
    @users = User.where("first_name ilike ? ","%#{search}%")
   # raise @users.inspect
   # where("first_name ILIKE ?", "%#{search}%") 
   # where("content LIKE ?", "%#{search}%")
  end
  
    
end

app/controllers/departments_users_controller.rb
class DepartmentsUsersController < ApplicationController
  before_filter :authorize
  
  
  def new
    
    @userdep = DepartmentsUser.new
    
  end
  
  def edit
    @departments = Department.all
       
    @userdep = User.find(params[:id])
   # raise @userdep.inspect  
  end
  
  def update
    ssss
    @userdep = User.find(params[:id])
     
       
       @user.update_attributes(user_params)
  end
  
  private
    def user_params
      fddgfg
      #raise params.inspect
    #  params.require(:user).permit(:first_name, :last_name,:domain_name,:email,:password,:password_confirmation,:is_admin,:status,:created_by,:updated_by)
      params.require(:user).permit!
    end
    
end

app/helpers/departments_users_helper.rb
module DepartmentsUsersHelper
end

app/views/departments_users/_edit.html.erb
<div class="modal-header" align ='center'>
  <h3><%= "Assigning Department to #{@userdep.first_name}" %></h3>
</div>
<%= render "form" %>

app/views/departments_users/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <%#raise @userdep.inspect%>
   <%= form_for(@userdep) do |u| %>
  <div class="modal-header">
    <h3>Assign Department To Users</h3>
  </div>
  <div class="modal-body">
       <table border="0" cellpadding="0" cellspacing ="0" width ="50%">
          
          <tbody>
               <%#= render "index_dep" %>
              
  
  
               <% for department in Department.all %>
                 <div>
                    <tr>
                      <td>   <%= check_box_tag "user[department_ids][]", department.id, @userdep.departments.include?(department) %> </td> 
                      <td>    <%= department.department_name %> </td> 
                    </tr>
                 </div>
               <% end %>
        
          </tbody>
        </table>
  </div>
  <div class="modal-footer">
       <%= link_to "Save", user_update_department_path(@user), method: :delete, remote: true, class: "btn btn-danger" %>
     <%#= u.submit ,{:value => "update"} %>
      <%#= link_to "Save", {:action => 'update',:controller => 'users' }, class: "btn" %>
     <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
  </div>
         <% end %>
  </div>
  
</div>

app/views/departments_users/_index_dep.html.erb
<% @departments.each do |department| %>
  <tr>
    <td> <%= check_box_tag :checkbox, "checkbox" %></td>
    <td> <%= department.department_name %></td>
    
  </tr>
 
<% end %>

app/views/departments_users/_save.js.erb
$("ul.errors").html("")
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".user-index").html("<%= escape_javascript(render 'index') %>")
  $("#user-modal").modal("hide")
<% end %>

app/views/departments_users/edit.js.erb
$("#user-modal").html("<%= escape_javascript(render 'edit') %>")
$("#user-modal").modal("show")

app/views/departments_users/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'new') %>")
$("#user-modal").modal("show")

app/views/departments_users/update.js.erb
<%= render "save" %>