config/routes.rb
Rails.application.routes.draw do

  
  get "log_out" => "logins#destroy", :as => "log_out"
  
  get "my_account" => "users#my_account"
    
  get "chnage_password" => "users#change_password"
  
  resources :users do
     get "delete"
     get "search_user_list"
     get "edit_department"
     post "update_department"
    collection { get :new_export }
   end
   
  resources :logins do
    
       
  end
 
  resources :sessions do
          get '/login' => 'sessions#new'
          post '/login' => 'sessions#create'
          get "index"
         
          post "new"
         
    end
     
  
   
  resources :users do
    collection do
      match 'search' => 'users#search', via: [:get, :post], as: :search
    end
  end
     
  resources :employees do
    get "import_index"
      collection { post :import }
     end
   
   resources :time_sheets do
    
       collection { post :import }
   end  
      
     
     get "time_home" => 'time_reports#time_home'
  
  resources :departments_users do
      
     
     collection { get :edit }
    end  
     
 root :to => "sessions#new"
      
      
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_and_belongs_to_many :departments
  
  has_many :login_details
  has_many :user_departments
   
   attr_accessor :password
   before_save :encrypt_password
  
    validates_presence_of :first_name 
    validates_presence_of :last_name
    validates_presence_of :email
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
    validates_uniqueness_of :email
    #validates_presence_of :domain_name
    validates_uniqueness_of :domain_name
    
 # validates_uniqueness_of :user_name
    
   # validates_presence_of :is_admin, :message => "/User Type? should be selected"
  require 'rubygems'
  
  require 'net/ldap' # gem install ruby-net-ldap
  require 'csv'
  
  SERVER = '172.28.48.51'
  PORT = 389
  BASE = 'tandon.local'
  DOMAIN = 'tandon.local'
  credentials = {
    :method => :simple,
    :username =>'suhas.dabhade@tandon.local',
    :password => 'Infinx@10'
  }
  
  
  def self.domain_authenticates(username,password)
    
      ldap = Net::LDAP.new :host => SERVER,:port => PORT, :base => BASE, :domain => DOMAIN,:auth => {
                                                                                           :method => :simple,
                                                                                           :username => username,
                                                                                           :password => password
                                                                                           }
          
                            
      if ldap.bind 
        
       # and user = ldap.search(:filter => "sAMAccountName=#{username}")
       
              # Redundant? Sure - the code will be 0 and the message will be "Success".
        puts "Connection successful!  Code:  #{ldap.get_operation_result.code}, message: #{ldap.get_operation_result.message}"
       
        # GET THE DISPLAY NAME AND E-MAIL ADDRESS FOR A SINGLE USER
       # search_param = username
       # result_attrs = ["displayName"]
        
        # Build filter
       # search_filter = Net::LDAP::Filter.eq("sAMAccountName", search_param)
        
        # Execute search
       # if ldap.search(:filter => search_filter, :attributes => result_attrs, :return_result => false)
        #  puts "SUHAS DABHADE"
          return true
      #  else
       #   puts "DABHADE SUHAS"
       #   return false
      #  end
      #  puts 'i am outside'
        
      else
        
        puts "Connection failed!  Code:  #{ldap.get_operation_result.code}, message: #{ldap.get_operation_result.message}"
        return false
      end
      
     
      
    end
    
    def self.domain_search(user1)
     
      ldap = Net::LDAP.new :host => SERVER,
           :port => 389,
           :auth => {
                       :method => :simple,
                       :username => 'suhas.dabhade@tandon.local',
                       :password => 'Infinx@10'
                    }
                    
      filter = Net::LDAP::Filter.eq( "sAMAccountName", user1 )
    # raise filter.inspect
      treebase = "tandon.local"
      
      ldap.search( :base => treebase, :filter => filter ) do |entry|
      raise entry.inspect
        puts "DN: #{entry.dn}"
        entry.each do |attribute, values|
          puts "   #{attribute}:"
          values.each do |value|
            puts "      --->#{value}"
          end
        end
      end
                   
                    
    end
     
     
  def self.db_authenticates(user)
    # raise user.inspect
       user = find_by_domain_name_and_status(user,'Active')
      # raise user.inspect
       if user
         user
       else
         nil
       end
     end
  
  
  def self.authenticate(username, password)
    
     user = find_by_user_name(username)
     if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
       user
     else
       nil
     end
   end
   
   def encrypt_password
     if password.present?
       self.password_salt = BCrypt::Engine.generate_salt
       self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
     end
   end

  
  
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |user|
        
        csv << user.attributes.values
      end
    end
  end
 
    
  def self.search(search)
    @users = User.where("first_name ilike ? ","%#{search}%")
   # raise @users.inspect
   # where("first_name ILIKE ?", "%#{search}%") 
   # where("content LIKE ?", "%#{search}%")
  end
  
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize
  
  def index
    #raise params.inspect
   # if params[:q] 
          @q = User.ransack(params[:q])
          #  raise @q.result.where("domain_name !=?",'').inspect
          @users = @q.result.where("domain_name !=?",'').paginate(page: params[:page], per_page: 4)
 # else     
        #  @userss = User.order(:id)
        #  @users1 = User.all.paginate(page: params[:page], per_page: 4)
 #  end
     
      respond_to do |format|
          format.html
          format.csv { send_data @users.to_csv }
          format.xls { send_data @users.to_csv(col_sep: "\t") }
       end
      
  
   end
 
   def show
     @user = User.find(params[:id])
   end
 
   def new
     @user = User.new
   end
 
   def create
     @users = User.all
     @user = User.create(user_params)
   end
 
   def edit
     @user = User.find(params[:id])
   end
 
   def update
     @users = User.all
     @user = User.find(params[:id])
     
    if  @user.update_attributes(user_params)
      redirect_to :action=>'index'
    end
     
   end
 
   def delete
     @user = User.find(params[:user_id])
   end
 
   def destroy
     @users = User.all
     @user = User.find(params[:id])
     @user.destroy
   end
   
  def new_export
    
  end
  
  
  def search_user_list
    defdfffre
    #raise params[:name].inspect
        @users = User.where("first_name ilike ? ","%#params[:name]")
  end
  
  def my_account
     
      # session[:patient_id] = nil
      @user = User.find(session[:user_id])
      @user.password = ''
     end
 
   def change_password
   end
   
   def edit_department
     @userdep = User.find(params[:user_id])
   end
   
   def update_department
    # params[:user][:department_ids] ||=[]
#raise params.inspect
    # @users = User.all
     @userdep = User.find(params[:user_id])
   
      @userdep.update_attributes(user_params1)
   end
  
  
 private
   def user_params
     #raise params.inspect
   #  params.require(:user).permit(:first_name, :last_name,:domain_name,:email,:password,:password_confirmation,:is_admin,:status,:created_by,:updated_by)
     params.require(:user).permit!
   end
  
  def user_params1
       #raise params.inspect
  params.require(:user).permit(:first_name, :last_name,:domain_name,:email,:password,:password_confirmation,:is_admin,:status,:created_by,:updated_by,:department_ids)
     #  params.require(:user).permit!
     end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete User</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @user.first_name %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This User", user_path(@user), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/users/_edit.html.erb
<div class="modal-header" align ='center'>
  <h3><%= "Editing #{@user.first_name}" %></h3>
</div>
<%= render "form" %>

app/views/users/_form.html.erb
<div class="modal-dialog">
  
  <div class="modal-content">
    <%= form_for @user, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>
        <table border="0" cellpadding="0" cellspacing ="0" width ="100%">
            <tbody>
              <tr>
                 <td class = "popuphd" bgcolor="#0588da" height =50 vailgn ="middle">
                     <strong>USER DETAILS</strong>
                  </td>
              </tr>
            </tbody>
           </table> </br>
           
        <div class="form-group">
          <span class="mandatory_color" style="color:red">*</span> <%= f.label :first_name, class:"control-label" %>
          <%= f.text_field :first_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <span class="mandatory_color" style="color:red">*</span> <%= f.label :last_name, class: "control-label" %>
          <%= f.text_field :last_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
         <span class="mandatory_color" style="color:red">*</span>  <%= f.label :email, class: "control-label" %>
          <%= f.text_field :email, class: "form-control" %>
        </div>
        
        <div class="form-group">
         <span class="mandatory_color" style="color:red">*</span>  <%= f.label :domain_name, class: "control-label" %>
          <%= f.text_field :domain_name, class: "form-control" %>
        </div>
        
        <div class="form-group">
          <%= f.label :is_admin, class: "control-label" %>
          <%= check_box('user','is_admin') %>
        </div>
        
        <div class="form-group">
          <%= f.label :status, class: "control-label" %>
          <%= f.select :status,"<option>Active</option><option>InActive</option>".html_safe%></P>
        </div>
        
      
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/users/_index.html.erb
<% @users.each do |user| %>
  <tr>
    <td><%= user.last_name.to_s.strip + ' ' +  user.first_name.to_s.strip  %></td>
    <td><%= user.email %></td>
    <td><%= user.domain_name %></td>
    <td><%= user.is_admin ? 'Yes' : 'No' %></td>
    <td><span id ='active' class ="Approve"> <%= user.status %> </span> </td>
    <td> <%#= link_to "Assign Departments", edit_departments_user_path(user), remote: true, class: "btn btn-primary"  %>  
    <%= link_to "Assign Departments", user_edit_department_path(user), remote: true, class: "btn btn-primary"  %>
    </td>
   
    <td><%= link_to "Edit", edit_user_path(user), remote: true, class: "btn btn-default"%></td>
    <td><%= link_to "Delete", user_delete_path(user), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/users/_save.js.erb
$("ul.errors").html("")
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".user-index").html("<%= escape_javascript(render 'index') %>")
  $("#user-modal").modal("hide")
<% end %>

app/views/users/_save_dep.js.erb
$("ul.errors").html("")
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".user-index").html("<%= escape_javascript(render 'index') %>")
  $("#user-modal").modal("hide")
<% end %>

app/views/users/create.js.erb
<%= render "save" %>

app/views/users/delete.js.erb
$("#user-modal").html("<%= escape_javascript(render 'delete') %>")
$("#user-modal").modal("show")

app/views/users/edit_department.js.erb
$("#user-modal").html("<%= escape_javascript(render 'edit_department') %>")
$("#user-modal").modal("show")

app/views/users/index.html.erb
<html>
<body>

</br>

<div class="container">

   <table border="0" cellspacing="0" cellpadding="0" width="100%">
                                <tr>
                                    <td align="left" class="heading" style="padding-top: 10px;">
                                        <strong>Manage Users</strong>
                                    </td>
                                </tr>
                                 
                                  <tr>
                                        <td align="center">&nbsp;</td>
                                   </tr>
                                 <div>
                                  <tr align="left">
                                      <td class="popupbg" style="padding: 10px;">
                                            
                                        <table>
                                           <%#= form_tag(users_path, :method => "get", id: "search-form") do %>
                                           <%= search_form_for @q do |f| %>
                                             <tr>
                                                <td align="left" width="05%">
                                                  <%= f.label :name %>
                                                </td>
                                                <td align="left" valign="middle" style="padding-left: 10px;" width="40%">
                                                 <%#= text_field "user", "name", "size" => 20 ,"style" => "width:230px;"%>
                                                 <%#= text_field_tag :search, params[:search], placeholder: "Search users" %>
                                                 <%= f.search_field :first_name_or_last_name_or_domain_name_cont %> (First Name, Last Name,domain_name) 
                                                </td>
                                                
                                                 <td align="left" width="06%">
                                                  <%= f.label :status %> <%#= f.label :status_cont %>
                                                </td>
                                                <td align="left" valign="middle" style="padding-left: 10px;" width="20%">
                                                     <%= f.select "status_cont","<option>Active</option><option>InActive</option>".html_safe%>

                                                </td>
                                                <td align="left" valign="middle" style="padding-left: 10px;" width="10%">
                                                  <%#= submit_tag "Search",{:class=>'buttons',:onclick=>"return loaduserdetails();"} %> 
                                                 <%#= image_submit_tag 'search.png',{:name => 'operation',:class => 'buttons', :id => 'text_value',:onclick=>"return loaduserdetails();"} %>
                                                  <%#= submit_tag "Search" %> 
                                                  <%= image_submit_tag 'search.png' %>
                                                 </td>
                                            </tr>
                                          <% end %>
                                        </table>
                                        
                                    </td>
                                 
                                  </tr>
                                  </div>
                                   <tr>
                                          <td height="25">&nbsp;</td>
                                    </tr>
   </table
       
  <div>
    <%= link_to "New User", new_user_path, remote: true, class: "btn btn-primary"  %>
     <%= link_to "Export",new_export_users_path,remote: true, class: "btn btn-primary"  %>
  </div>
  <br>
  <div class="new-user"></div>
  <div class="container" > 
      <table align = "right" border = "0">
               <tbody>
                 <tr>
                     <td>
                      <b> <%= will_paginate @user ,:next_label => "&gt;&gt;" ,:previous_label => "&lt;&lt;" %> </b>
                      </td>
                   <tr>
                </tbody>
        </table>
  <table class="table table-bordered table-striped">
    <thead>
     
      <tr>
      
        <th width="20%" height="5" align="left"  valign="middle" bgcolor="#0370b5" class="whitetext">Name</th>
        <th width="20%" height="28" align="left" valign="middle" bgcolor="#0370b5" class="whitetext">Email Id</th>
        <th width="20%" height="28" align="left" valign="middle" bgcolor="#0370b5" class="whitetext">Domain name</th>
        <th width="20%" height="28" align="left" valign="middle" bgcolor="#0370b5" class="whitetext">Is admin</th>
        <th width="20%" height="28" align="left" valign="middle" bgcolor="#0370b5" class="whitetext">Status</th>
        <td width="20%" height="28" align="left" valign="middle" bgcolor="#0370b5" class="whitetext">&nbsp;</td>
        <td width="20%" height="28" align="left" valign="middle" bgcolor="#0370b5" class="whitetext">&nbsp;</td>
        <td width="20%" height="28" align="left" valign="middle" bgcolor="#0370b5" class="whitetext">&nbsp;</td>
      </tr>
    </thead>
    <tbody class="user-index">
      <%= render "index" %>
    </tbody>
  </table>
   
   
   <table align = "right" border = "0">
               <tbody>
                 <tr>
                     <td>
                        <b> <%= will_paginate @user ,:next_label => "&gt;&gt;" ,:previous_label => "&lt;&lt;" %> </b>
                      </td>
                   <tr>
                </tbody>
        </table>
        
   </table>


</div>

 
<div id="user-modal" class="modal fade"></div>
</div>

</html>
</body>

<script  type="text/javascript">

         function loaduserdetails()
          {
                   alert ('hi');
              //  var pars = document.getElementById("user_name").value;
               var pars = "name=" + $F('user_name');
               var myAjax = new Ajax.Updater("users",'/users/search_user_list',{
               parameters:pars,
               method:'get'
               });
               
           }

</script>





 

app/views/users/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'new') %>")
$("#user-modal").modal("show")

app/views/users/new_export.js.erb
$("#user-modal").html("<%= escape_javascript(render 'new_export') %>")
$("#user-modal").modal("show")

app/views/users/update.js.erb
<%= render "save" %>